### ISSUE TITLE
illegal reflective warnings

### ISSUE THREAD

**Issue by mguilherme** [yschimke/okurl-scripts#3]
Not sure if there's a simple way to disable the "An illegal reflective access operation has occurred" warnings.
Is there a way of disabling this warnings? Kotlin Scripts seems great but this warnings are pouting the std out.
Not sure how they manage to disable this but last time I use kscript this warnings were not present:

```console
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.ReflectionUtil (file:/Users/some-user/.sdkman/candidates/kotlin/1.4.21/lib/kotlin-compiler.jar) to method java.util.ResourceBundle.setParent(java.util.ResourceBundle)
WARNING: Please consider reporting this to the maintainers of com.intellij.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by yschimke** [comment]
Running with JDK8 can be an option, but I've also started building some things with JDK11, so it's possible I've broken this option.

**Comment by yschimke** [comment]
https://youtrack.jetbrains.com/issue/KT-43520

**Comment by mguilherme** [comment]
Thanks for the replies 🙂 I also tried with jdk11, the warning still remains, this happens with all my scripts Not just yours.

Guess we have to live with these warnings for now 😢

**Comment by yschimke** [comment]
For now, must make sure you set JAVA_HOME to 1.8 if you want to avoid.  And avoid dependencies on Java 11.  IT's working without any warnings for me.

**Comment by mguilherme** [comment]
The way I’m now avoiding the warnings is to use `—add-opens`, I switched my shebang to:

`#!/usr/bin/env kotlinc -J--add-opens=java.base/java.util=ALL-UNNAMED -script `

**Comment by yschimke** [comment]
It's so unsatisfactory to have to curate this list as you evolve the script. Needs fix in Kotlin instead.

**Comment by mguilherme** [comment]
Totally agree
